### ISSUE TITLE
[Help with]fbmessenger not working 100%

### ISSUE THREAD

**Issue by DevDorrejo** [LiveHelperChat/fbmessenger#22]
Hello, i have setup this extension and is not totally working.
php: 7.3
apache: 2.4.43
mariadb: 10.4.14
LHC v: 3.42/Master
vhost:
```
1 <IfModule mod_ssl.c>
2 <VirtualHost *:443>
3     ServerName chat.example.org
4
5     DocumentRoot /services/webs/chat
6
7     ErrorLog /var/log/apache2/chat_error_log
8     CustomLog /var/log/apache2/chat_access_log combined
9
10     # don't loose time with IP address lookups
11     HostnameLookups Off
12
13     # needed for named virtual hosts
14     UseCanonicalName Off
15
16     # configures the footer on server-generated documents
17     ServerSignature On
18
19     <Directory "/services/webs/chat">
20
21         Options -Indexes +FollowSymLinks +MultiViews
22
23         AllowOverride All
24
25         <IfModule !mod_access_compat.c>
26             Require all granted
27         </IfModule>
28         <IfModule mod_access_compat.c>
29             Order allow,deny
30             Allow from all
31         </IfModule>
32
33     </Directory>
34
35
36 SSLCertificateFile letsencrypt
37 SSLCertificateKeyFile letsencrypt
38 Include /etc/letsencrypt/options-ssl-apache.conf
39 </VirtualHost>
40 </IfModule>
```

debug.log: this error appear when i write a message from fb to the bot
```
Sep 27 16:20:23 [Warning] [default] [default] Error Object
(
[message:protected] => Call to undefined function fastcgi_finish_request()
[string:Error:private] => Error: Call to undefined function fastcgi_finish_request() in /services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1
Stack trace:
#0 /services/webs/chat/lib/core/lhcore/lhmodule.php(96): include()
#1 /services/webs/chat/lib/core/lhcore/lhmodule.php(550): erLhcoreClassModule::runModule()
#2 /services/webs/chat/index.php(44): erLhcoreClassModule::moduleInit()
#3 {main}
[code:protected] => 0
[file:protected] => /services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php
[line:protected] => 1
[trace:Error:private] => Array
(
[0] => Array
(
[file] => /services/webs/chat/lib/core/lhcore/lhmodule.php
[line] => 96
[function] => include
)

[1] => Array
(
[file] => /services/webs/chat/lib/core/lhcore/lhmodule.php
[line] => 550
[function] => runModule
[class] => erLhcoreClassModule
[type] => ::
[args] => Array
(
)

)

[2] => Array
(
[file] => /services/webs/chat/index.php
[line] => 44
[function] => moduleInit
[class] => erLhcoreClassModule
[type] => ::
[args] => Array
(
)

)

)

[previous:Error:private] => 
)
Sep 27 16:20:24 [Warning] [default] [default] Error Object
(
[message:protected] => Call to undefined function fastcgi_finish_request()
[string:Error:private] => Error: Call to undefined function fastcgi_finish_request() in /services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1
Stack trace:
#0 /services/webs/chat/lib/core/lhcore/lhmodule.php(96): include()
#1 /services/webs/chat/lib/core/lhcore/lhmodule.php(550): erLhcoreClassModule::runModule()
#2 /services/webs/chat/index.php(44): erLhcoreClassModule::moduleInit()
#3 {main}
[code:protected] => 0
[file:protected] => /services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php
[line:protected] => 1
[trace:Error:private] => Array
(
[0] => Array
(
[file] => /services/webs/chat/lib/core/lhcore/lhmodule.php
[line] => 96
[function] => include
)

[1] => Array
(
[file] => /services/webs/chat/lib/core/lhcore/lhmodule.php
[line] => 550
[function] => runModule
[class] => erLhcoreClassModule
[type] => ::
[args] => Array
(
)

)

[2] => Array
(
[file] => /services/webs/chat/index.php
[line] => 44
[function] => moduleInit
[class] => erLhcoreClassModule
[type] => ::
[args] => Array
(
)

)

)

[previous:Error:private] =>
)
```

apache error_log:

```
[Sun Sep 27 11:28:42.046631 2020] [php7:notice] [pid 1128] [client 69.171.251.3:55554] Error: Call to undefined function fastcgi_finish_request() in /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1\nStacktrace:\n#0 /opt/services/webs/chat/lib/core/lhcore/lhmodule.php(96): include()\n#1 /opt/services/webs/chat/lib/core/lhcore/lhmodule.php(550): erLhcoreClassModule::runModule()\n#2 /opt/services/webs/chat/index.php(44): erLhcoreClassModule::moduleInit()\n#3 {main}
[Sun Sep 27 11:28:42.046665 2020] [php7:warn] [pid 1128] [client 69.171.251.3:55554] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1) in /opt/services/webs/chat/lib/core/lhcore/lhmodule.php on line 192
[Sun Sep 27 11:28:42.046675 2020] [php7:warn] [pid 1128] [client 69.171.251.3:55554] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1) in /opt/services/webs/chat/lib/core/lhcore/lhmodule.php on line 193
[Sun Sep 27 11:28:42.046683 2020] [php7:warn] [pid 1128] [client 69.171.251.3:55554] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1) in /opt/services/webs/chat/lib/core/lhcore/lhmodule.php on line 194
[Sun Sep 27 11:28:42.261690 2020] [php7:notice] [pid 1132] [client 173.252.127.13:35400] Error: Call to undefined function fastcgi_finish_request() in /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1\nStack trace:\n#0 /opt/services/webs/chat/lib/core/lhcore/lhmodule.php(96): include()\n#1 /opt/services/webs/chat/lib/core/lhcore/lhmodule.php(550): erLhcoreClassModule::runModule()\n#2 /opt/services/webs/chat/index.php(44): erLhcoreClassModule::moduleInit()\n#3 {main}
[Sun Sep 27 11:28:42.261750 2020] [php7:warn] [pid 1132] [client 173.252.127.13:35400] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1) in /opt/services/webs/chat/lib/core/lhcore/lhmodule.php on line 192
[Sun Sep 27 11:28:42.261787 2020] [php7:warn] [pid 1132] [client 173.252.127.13:35400] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1) in /opt/services/webs/chat/lib/core/lhcore/lhmodule.php on line 193
[Sun Sep 27 11:28:42.261827 2020] [php7:warn] [pid 1132] [client 173.252.127.13:35400] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/services/webs/chat/cache/compiledtemplates/aa9635868b34ce13b688dde758165a06.php:1) in /opt/services/webs/chat/lib/core/lhcore/lhmodule.php on line 194
```
What work?

* Add Start Burron.

Preview of the trigger

![image](https://user-images.githubusercontent.com/7697566/94370245-e45bb880-00bc-11eb-9140-1e165ce464ec.png)

**Comment by remdex** [comment]
This one I'll check tomorrow.

**Comment by DevDorrejo** [comment]
> This one I'll check tomorrow.

ok, thank you very much
